
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: foodlyst-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: param9999/restaurant-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8079
          env:
            # =========================
            # CONFIG SERVER
            # =========================
            - name: CONFIG_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: config-service-secret
                  key: CONFIG_SERVER_HOST

            # =========================
            # MYSQL CONFIG
            # =========================
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "restaurant"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "rootpassword"

            # =========================
            # EUREKA
            # =========================
            - name: EUREKA_URL
              value: "eureka-server"

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: foodlyst-microservice
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 8079
      targetPort: 8079
  type: NodePort
